// Copyright 2026 GOCO-AI. All rights reserved.
// Use of this source code is governed by an MIT-style license.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.3
// source: grpc/proto/emcpv1/transport.proto

package emcpv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MCPMessage carries a single JSON-RPC message as an opaque byte payload.
// The payload is produced by jsonrpc.EncodeMessage and consumed by
// jsonrpc.DecodeMessage — the gRPC layer never inspects its contents.
type MCPMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *MCPMessage) Reset() {
	*x = MCPMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_emcpv1_transport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MCPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPMessage) ProtoMessage() {}

func (x *MCPMessage) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_emcpv1_transport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPMessage.ProtoReflect.Descriptor instead.
func (*MCPMessage) Descriptor() ([]byte, []int) {
	return file_grpc_proto_emcpv1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *MCPMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_grpc_proto_emcpv1_transport_proto protoreflect.FileDescriptor

var file_grpc_proto_emcpv1_transport_proto_rawDesc = []byte{
	0x0a, 0x21, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x63,
	0x70, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x6d, 0x63, 0x70, 0x2e, 0x76, 0x31, 0x22, 0x26, 0x0a, 0x0a,
	0x4d, 0x43, 0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x32, 0x46, 0x0a, 0x0c, 0x4d, 0x43, 0x50, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x13,
	0x2e, 0x65, 0x6d, 0x63, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x43, 0x50, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x13, 0x2e, 0x65, 0x6d, 0x63, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x43,
	0x50, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2e, 0x5a, 0x2c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x63, 0x6f, 0x2d,
	0x61, 0x69, 0x2f, 0x65, 0x6d, 0x63, 0x70, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x63, 0x70, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_emcpv1_transport_proto_rawDescOnce sync.Once
	file_grpc_proto_emcpv1_transport_proto_rawDescData = file_grpc_proto_emcpv1_transport_proto_rawDesc
)

func file_grpc_proto_emcpv1_transport_proto_rawDescGZIP() []byte {
	file_grpc_proto_emcpv1_transport_proto_rawDescOnce.Do(func() {
		file_grpc_proto_emcpv1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_emcpv1_transport_proto_rawDescData)
	})
	return file_grpc_proto_emcpv1_transport_proto_rawDescData
}

var file_grpc_proto_emcpv1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpc_proto_emcpv1_transport_proto_goTypes = []interface{}{
	(*MCPMessage)(nil), // 0: emcp.v1.MCPMessage
}
var file_grpc_proto_emcpv1_transport_proto_depIdxs = []int32{
	0, // 0: emcp.v1.MCPTransport.Stream:input_type -> emcp.v1.MCPMessage
	0, // 1: emcp.v1.MCPTransport.Stream:output_type -> emcp.v1.MCPMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_proto_emcpv1_transport_proto_init() }
func file_grpc_proto_emcpv1_transport_proto_init() {
	if File_grpc_proto_emcpv1_transport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_emcpv1_transport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MCPMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_emcpv1_transport_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_emcpv1_transport_proto_goTypes,
		DependencyIndexes: file_grpc_proto_emcpv1_transport_proto_depIdxs,
		MessageInfos:      file_grpc_proto_emcpv1_transport_proto_msgTypes,
	}.Build()
	File_grpc_proto_emcpv1_transport_proto = out.File
	file_grpc_proto_emcpv1_transport_proto_rawDesc = nil
	file_grpc_proto_emcpv1_transport_proto_goTypes = nil
	file_grpc_proto_emcpv1_transport_proto_depIdxs = nil
}
