// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: grpc/proto/emcpv1/transport.proto

package emcpv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MCPTransportClient is the client API for MCPTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MCPTransportClient interface {
	// Stream opens a persistent bidirectional channel. Both sides send and
	// receive MCPMessage frames for the lifetime of the MCP session.
	Stream(ctx context.Context, opts ...grpc.CallOption) (MCPTransport_StreamClient, error)
}

type mCPTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewMCPTransportClient(cc grpc.ClientConnInterface) MCPTransportClient {
	return &mCPTransportClient{cc}
}

func (c *mCPTransportClient) Stream(ctx context.Context, opts ...grpc.CallOption) (MCPTransport_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MCPTransport_ServiceDesc.Streams[0], "/emcp.v1.MCPTransport/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &mCPTransportStreamClient{stream}
	return x, nil
}

type MCPTransport_StreamClient interface {
	Send(*MCPMessage) error
	Recv() (*MCPMessage, error)
	grpc.ClientStream
}

type mCPTransportStreamClient struct {
	grpc.ClientStream
}

func (x *mCPTransportStreamClient) Send(m *MCPMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mCPTransportStreamClient) Recv() (*MCPMessage, error) {
	m := new(MCPMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MCPTransportServer is the server API for MCPTransport service.
// All implementations must embed UnimplementedMCPTransportServer
// for forward compatibility
type MCPTransportServer interface {
	// Stream opens a persistent bidirectional channel. Both sides send and
	// receive MCPMessage frames for the lifetime of the MCP session.
	Stream(MCPTransport_StreamServer) error
	mustEmbedUnimplementedMCPTransportServer()
}

// UnimplementedMCPTransportServer must be embedded to have forward compatible implementations.
type UnimplementedMCPTransportServer struct {
}

func (UnimplementedMCPTransportServer) Stream(MCPTransport_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedMCPTransportServer) mustEmbedUnimplementedMCPTransportServer() {}

// UnsafeMCPTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCPTransportServer will
// result in compilation errors.
type UnsafeMCPTransportServer interface {
	mustEmbedUnimplementedMCPTransportServer()
}

func RegisterMCPTransportServer(s grpc.ServiceRegistrar, srv MCPTransportServer) {
	s.RegisterService(&MCPTransport_ServiceDesc, srv)
}

func _MCPTransport_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MCPTransportServer).Stream(&mCPTransportStreamServer{stream})
}

type MCPTransport_StreamServer interface {
	Send(*MCPMessage) error
	Recv() (*MCPMessage, error)
	grpc.ServerStream
}

type mCPTransportStreamServer struct {
	grpc.ServerStream
}

func (x *mCPTransportStreamServer) Send(m *MCPMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mCPTransportStreamServer) Recv() (*MCPMessage, error) {
	m := new(MCPMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MCPTransport_ServiceDesc is the grpc.ServiceDesc for MCPTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCPTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emcp.v1.MCPTransport",
	HandlerType: (*MCPTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _MCPTransport_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc/proto/emcpv1/transport.proto",
}
