// MCP protocol schema based on the MCP specification:
// https://modelcontextprotocol.io/specification/2026-07-28/
// Last Updated on: 2026-07-20

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: mcp.proto

package mcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_mcp_proto protoreflect.FileDescriptor

const file_mcp_proto_rawDesc = "" +
	"\n" +
	"\tmcp.proto\x12\x16model_context_protocol\x1a\x12mcp_messages.proto2\xd3\x06\n" +
	"\x03Mcp\x12l\n" +
	"\rListResources\x12,.model_context_protocol.ListResourcesRequest\x1a-.model_context_protocol.ListResourcesResponse\x12i\n" +
	"\fReadResource\x12+.model_context_protocol.ReadResourceRequest\x1a,.model_context_protocol.ReadResourceResponse\x12\x84\x01\n" +
	"\x15ListResourceTemplates\x124.model_context_protocol.ListResourceTemplatesRequest\x1a5.model_context_protocol.ListResourceTemplatesResponse\x12f\n" +
	"\vListPrompts\x12*.model_context_protocol.ListPromptsRequest\x1a+.model_context_protocol.ListPromptsResponse\x12`\n" +
	"\tGetPrompt\x12(.model_context_protocol.GetPromptRequest\x1a).model_context_protocol.GetPromptResponse\x12`\n" +
	"\tListTools\x12(.model_context_protocol.ListToolsRequest\x1a).model_context_protocol.ListToolsResponse\x12]\n" +
	"\bCallTool\x12'.model_context_protocol.CallToolRequest\x1a(.model_context_protocol.CallToolResponse\x12a\n" +
	"\bComplete\x12).model_context_protocol.CompletionRequest\x1a*.model_context_protocol.CompletionResponseB\xd0\x01\n" +
	"\x1acom.model_context_protocolB\bMcpProtoP\x01Z8github.com/grpmsoft/emcp-go/grpc/typed/proto/mcppb;mcppb\xa2\x02\x03MXX\xaa\x02\x14ModelContextProtocol\xca\x02\x14ModelContextProtocol\xe2\x02 ModelContextProtocol\\GPBMetadata\xea\x02\x14ModelContextProtocolb\x06proto3"

var file_mcp_proto_goTypes = []any{
	(*ListResourcesRequest)(nil),          // 0: model_context_protocol.ListResourcesRequest
	(*ReadResourceRequest)(nil),           // 1: model_context_protocol.ReadResourceRequest
	(*ListResourceTemplatesRequest)(nil),  // 2: model_context_protocol.ListResourceTemplatesRequest
	(*ListPromptsRequest)(nil),            // 3: model_context_protocol.ListPromptsRequest
	(*GetPromptRequest)(nil),              // 4: model_context_protocol.GetPromptRequest
	(*ListToolsRequest)(nil),              // 5: model_context_protocol.ListToolsRequest
	(*CallToolRequest)(nil),               // 6: model_context_protocol.CallToolRequest
	(*CompletionRequest)(nil),             // 7: model_context_protocol.CompletionRequest
	(*ListResourcesResponse)(nil),         // 8: model_context_protocol.ListResourcesResponse
	(*ReadResourceResponse)(nil),          // 9: model_context_protocol.ReadResourceResponse
	(*ListResourceTemplatesResponse)(nil), // 10: model_context_protocol.ListResourceTemplatesResponse
	(*ListPromptsResponse)(nil),           // 11: model_context_protocol.ListPromptsResponse
	(*GetPromptResponse)(nil),             // 12: model_context_protocol.GetPromptResponse
	(*ListToolsResponse)(nil),             // 13: model_context_protocol.ListToolsResponse
	(*CallToolResponse)(nil),              // 14: model_context_protocol.CallToolResponse
	(*CompletionResponse)(nil),            // 15: model_context_protocol.CompletionResponse
}
var file_mcp_proto_depIdxs = []int32{
	0,  // 0: model_context_protocol.Mcp.ListResources:input_type -> model_context_protocol.ListResourcesRequest
	1,  // 1: model_context_protocol.Mcp.ReadResource:input_type -> model_context_protocol.ReadResourceRequest
	2,  // 2: model_context_protocol.Mcp.ListResourceTemplates:input_type -> model_context_protocol.ListResourceTemplatesRequest
	3,  // 3: model_context_protocol.Mcp.ListPrompts:input_type -> model_context_protocol.ListPromptsRequest
	4,  // 4: model_context_protocol.Mcp.GetPrompt:input_type -> model_context_protocol.GetPromptRequest
	5,  // 5: model_context_protocol.Mcp.ListTools:input_type -> model_context_protocol.ListToolsRequest
	6,  // 6: model_context_protocol.Mcp.CallTool:input_type -> model_context_protocol.CallToolRequest
	7,  // 7: model_context_protocol.Mcp.Complete:input_type -> model_context_protocol.CompletionRequest
	8,  // 8: model_context_protocol.Mcp.ListResources:output_type -> model_context_protocol.ListResourcesResponse
	9,  // 9: model_context_protocol.Mcp.ReadResource:output_type -> model_context_protocol.ReadResourceResponse
	10, // 10: model_context_protocol.Mcp.ListResourceTemplates:output_type -> model_context_protocol.ListResourceTemplatesResponse
	11, // 11: model_context_protocol.Mcp.ListPrompts:output_type -> model_context_protocol.ListPromptsResponse
	12, // 12: model_context_protocol.Mcp.GetPrompt:output_type -> model_context_protocol.GetPromptResponse
	13, // 13: model_context_protocol.Mcp.ListTools:output_type -> model_context_protocol.ListToolsResponse
	14, // 14: model_context_protocol.Mcp.CallTool:output_type -> model_context_protocol.CallToolResponse
	15, // 15: model_context_protocol.Mcp.Complete:output_type -> model_context_protocol.CompletionResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	file_mcp_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
