// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.3
// source: grpc/typed/proto/mcppb/mcp.proto

package mcppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// McpClient is the client API for Mcp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpClient interface {
	// ListTools returns all tools registered on the server.
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// CallTool invokes a named tool with the given arguments.
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
}

type mcpClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpClient(cc grpc.ClientConnInterface) McpClient {
	return &mcpClient{cc}
}

func (c *mcpClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, "/mcppb.Mcp/ListTools", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, "/mcppb.Mcp/CallTool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpServer is the server API for Mcp service.
// All implementations must embed UnimplementedMcpServer
// for forward compatibility
type McpServer interface {
	// ListTools returns all tools registered on the server.
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// CallTool invokes a named tool with the given arguments.
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	mustEmbedUnimplementedMcpServer()
}

// UnimplementedMcpServer must be embedded to have forward compatible implementations.
type UnimplementedMcpServer struct {
}

func (UnimplementedMcpServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedMcpServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedMcpServer) mustEmbedUnimplementedMcpServer() {}

// UnsafeMcpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpServer will
// result in compilation errors.
type UnsafeMcpServer interface {
	mustEmbedUnimplementedMcpServer()
}

func RegisterMcpServer(s grpc.ServiceRegistrar, srv McpServer) {
	s.RegisterService(&Mcp_ServiceDesc, srv)
}

func _Mcp_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcppb.Mcp/ListTools",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mcppb.Mcp/CallTool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mcp_ServiceDesc is the grpc.ServiceDesc for Mcp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mcp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcppb.Mcp",
	HandlerType: (*McpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTools",
			Handler:    _Mcp_ListTools_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _Mcp_CallTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/typed/proto/mcppb/mcp.proto",
}
