// MCP protocol schema based on the MCP specification:
// https://modelcontextprotocol.io/specification/2026-07-28/
// Last Updated on: 2026-07-20

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: mcp.proto

package mcppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mcp_ListResources_FullMethodName         = "/model_context_protocol.Mcp/ListResources"
	Mcp_ReadResource_FullMethodName          = "/model_context_protocol.Mcp/ReadResource"
	Mcp_ListResourceTemplates_FullMethodName = "/model_context_protocol.Mcp/ListResourceTemplates"
	Mcp_ListPrompts_FullMethodName           = "/model_context_protocol.Mcp/ListPrompts"
	Mcp_GetPrompt_FullMethodName             = "/model_context_protocol.Mcp/GetPrompt"
	Mcp_ListTools_FullMethodName             = "/model_context_protocol.Mcp/ListTools"
	Mcp_CallTool_FullMethodName              = "/model_context_protocol.Mcp/CallTool"
	Mcp_Complete_FullMethodName              = "/model_context_protocol.Mcp/Complete"
)

// McpClient is the client API for Mcp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type McpClient interface {
	// List resources.
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	// Read a resource.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_resource whose value is the name of the resource being requested.
	ReadResource(ctx context.Context, in *ReadResourceRequest, opts ...grpc.CallOption) (*ReadResourceResponse, error)
	// List resource templates.
	ListResourceTemplates(ctx context.Context, in *ListResourceTemplatesRequest, opts ...grpc.CallOption) (*ListResourceTemplatesResponse, error)
	// List prompts.
	ListPrompts(ctx context.Context, in *ListPromptsRequest, opts ...grpc.CallOption) (*ListPromptsResponse, error)
	// Get a prompt.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_prompt whose value is the name of the prompt being requested.
	GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*GetPromptResponse, error)
	// List tools.
	ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error)
	// Call a tool.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_tool whose value is the name of the tool being called.
	CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error)
	// Requests completions.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_resource whose value is the name of the resource or prompt being
	// used for completion.
	Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error)
}

type mcpClient struct {
	cc grpc.ClientConnInterface
}

func NewMcpClient(cc grpc.ClientConnInterface) McpClient {
	return &mcpClient{cc}
}

func (c *mcpClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, Mcp_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) ReadResource(ctx context.Context, in *ReadResourceRequest, opts ...grpc.CallOption) (*ReadResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResourceResponse)
	err := c.cc.Invoke(ctx, Mcp_ReadResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) ListResourceTemplates(ctx context.Context, in *ListResourceTemplatesRequest, opts ...grpc.CallOption) (*ListResourceTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceTemplatesResponse)
	err := c.cc.Invoke(ctx, Mcp_ListResourceTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) ListPrompts(ctx context.Context, in *ListPromptsRequest, opts ...grpc.CallOption) (*ListPromptsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPromptsResponse)
	err := c.cc.Invoke(ctx, Mcp_ListPrompts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) GetPrompt(ctx context.Context, in *GetPromptRequest, opts ...grpc.CallOption) (*GetPromptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPromptResponse)
	err := c.cc.Invoke(ctx, Mcp_GetPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) ListTools(ctx context.Context, in *ListToolsRequest, opts ...grpc.CallOption) (*ListToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListToolsResponse)
	err := c.cc.Invoke(ctx, Mcp_ListTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) CallTool(ctx context.Context, in *CallToolRequest, opts ...grpc.CallOption) (*CallToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallToolResponse)
	err := c.cc.Invoke(ctx, Mcp_CallTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcpClient) Complete(ctx context.Context, in *CompletionRequest, opts ...grpc.CallOption) (*CompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompletionResponse)
	err := c.cc.Invoke(ctx, Mcp_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McpServer is the server API for Mcp service.
// All implementations must embed UnimplementedMcpServer
// for forward compatibility.
type McpServer interface {
	// List resources.
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	// Read a resource.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_resource whose value is the name of the resource being requested.
	ReadResource(context.Context, *ReadResourceRequest) (*ReadResourceResponse, error)
	// List resource templates.
	ListResourceTemplates(context.Context, *ListResourceTemplatesRequest) (*ListResourceTemplatesResponse, error)
	// List prompts.
	ListPrompts(context.Context, *ListPromptsRequest) (*ListPromptsResponse, error)
	// Get a prompt.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_prompt whose value is the name of the prompt being requested.
	GetPrompt(context.Context, *GetPromptRequest) (*GetPromptResponse, error)
	// List tools.
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
	// Call a tool.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_tool whose value is the name of the tool being called.
	CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error)
	// Requests completions.
	// In order to better integrate with existing data plane mechanisms for
	// request routing and authz, the client will add a header called
	// mcp_resource whose value is the name of the resource or prompt being
	// used for completion.
	Complete(context.Context, *CompletionRequest) (*CompletionResponse, error)
	mustEmbedUnimplementedMcpServer()
}

// UnimplementedMcpServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMcpServer struct{}

func (UnimplementedMcpServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedMcpServer) ReadResource(context.Context, *ReadResourceRequest) (*ReadResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadResource not implemented")
}
func (UnimplementedMcpServer) ListResourceTemplates(context.Context, *ListResourceTemplatesRequest) (*ListResourceTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResourceTemplates not implemented")
}
func (UnimplementedMcpServer) ListPrompts(context.Context, *ListPromptsRequest) (*ListPromptsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPrompts not implemented")
}
func (UnimplementedMcpServer) GetPrompt(context.Context, *GetPromptRequest) (*GetPromptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrompt not implemented")
}
func (UnimplementedMcpServer) ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTools not implemented")
}
func (UnimplementedMcpServer) CallTool(context.Context, *CallToolRequest) (*CallToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedMcpServer) Complete(context.Context, *CompletionRequest) (*CompletionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedMcpServer) mustEmbedUnimplementedMcpServer() {}
func (UnimplementedMcpServer) testEmbeddedByValue()             {}

// UnsafeMcpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to McpServer will
// result in compilation errors.
type UnsafeMcpServer interface {
	mustEmbedUnimplementedMcpServer()
}

func RegisterMcpServer(s grpc.ServiceRegistrar, srv McpServer) {
	// If the following call panics, it indicates UnimplementedMcpServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mcp_ServiceDesc, srv)
}

func _Mcp_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_ReadResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).ReadResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_ReadResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).ReadResource(ctx, req.(*ReadResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_ListResourceTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).ListResourceTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_ListResourceTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).ListResourceTemplates(ctx, req.(*ListResourceTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_ListPrompts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPromptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).ListPrompts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_ListPrompts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).ListPrompts(ctx, req.(*ListPromptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_GetPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).GetPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_GetPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).GetPrompt(ctx, req.(*GetPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_ListTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).ListTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_ListTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).ListTools(ctx, req.(*ListToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_CallTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).CallTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_CallTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).CallTool(ctx, req.(*CallToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mcp_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McpServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mcp_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McpServer).Complete(ctx, req.(*CompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mcp_ServiceDesc is the grpc.ServiceDesc for Mcp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mcp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model_context_protocol.Mcp",
	HandlerType: (*McpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResources",
			Handler:    _Mcp_ListResources_Handler,
		},
		{
			MethodName: "ReadResource",
			Handler:    _Mcp_ReadResource_Handler,
		},
		{
			MethodName: "ListResourceTemplates",
			Handler:    _Mcp_ListResourceTemplates_Handler,
		},
		{
			MethodName: "ListPrompts",
			Handler:    _Mcp_ListPrompts_Handler,
		},
		{
			MethodName: "GetPrompt",
			Handler:    _Mcp_GetPrompt_Handler,
		},
		{
			MethodName: "ListTools",
			Handler:    _Mcp_ListTools_Handler,
		},
		{
			MethodName: "CallTool",
			Handler:    _Mcp_CallTool_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _Mcp_Complete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mcp.proto",
}
